"""Pure value models reused across the package: paths, references, attributes.

No nodes and no IO. The node *spine* is the v5 `graph` layer (`NodeRecord` /
`NodeTree`); this package holds the camelCase-aliased OME value objects — document
paths, the portable `ReferenceObj`, and the typed attribute models — that nodes
carry and that validation reads.
"""

from ngio_collections.models._config import BaseObj, NodeStateError
from ngio_collections.models._paths import (
    DocPath,
    JsonPath,
    PathObj,
    ZarrPath,
)
from ngio_collections.models._references import IdStr, ReferenceObj
from ngio_collections.models.attributes import (
    AcquisitionAttribute,
    AcquisitionObj,
    AffineTransformation,
    AnyAttribute,
    AttributeType,
    Axis,
    BaseAttribute,
    BaseListAttribute,
    BijectionTransformation,
    ByDimensionItem,
    ByDimensionTransformation,
    ColumnObj,
    CoordinateSystem,
    CoordinateSystemsAttribute,
    CoordinatesTransformation,
    CoordinateTransformation,
    CoordinateTransformationsAttribute,
    CustomTransformation,
    DisplacementsTransformation,
    IdentityTransformation,
    LabelObj,
    LabelsAttribute,
    MapAxisTransformation,
    PlateAttribute,
    RgbaColor,
    RotationTransformation,
    RowObj,
    ScaleTransformation,
    SceneAttribute,
    SequenceTransformation,
    TranslationTransformation,
    WellAttribute,
)

__all__ = [
    "AcquisitionAttribute",
    "AcquisitionObj",
    "AffineTransformation",
    "AnyAttribute",
    "AttributeType",
    "Axis",
    "BaseAttribute",
    "BaseListAttribute",
    "BaseObj",
    "BijectionTransformation",
    "ByDimensionItem",
    "ByDimensionTransformation",
    "ColumnObj",
    "CoordinateSystem",
    "CoordinateSystemsAttribute",
    "CoordinateTransformation",
    "CoordinateTransformationsAttribute",
    "CoordinatesTransformation",
    "CustomTransformation",
    "DisplacementsTransformation",
    "DocPath",
    "IdStr",
    "IdentityTransformation",
    "JsonPath",
    "LabelObj",
    "LabelsAttribute",
    "MapAxisTransformation",
    "NodeStateError",
    "PathObj",
    "PlateAttribute",
    "ReferenceObj",
    "RgbaColor",
    "RotationTransformation",
    "RowObj",
    "ScaleTransformation",
    "SceneAttribute",
    "SequenceTransformation",
    "TranslationTransformation",
    "WellAttribute",
    "ZarrPath",
]
